config/routes.rb
Rails.application.routes.draw do
  resources :greeting_cards
  get 'home/index'
  root 'greeting_cards#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/greeting_card.rb
class GreetingCard < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/greeting_cards_controller.rb
class GreetingCardsController < ApplicationController
  before_action :set_greeting_card, only: [:show, :edit, :update, :destroy]

  # GET /greeting_cards
  # GET /greeting_cards.json
  def index
    @greeting_cards = GreetingCard.all
  end

  # GET /greeting_cards/1
  # GET /greeting_cards/1.json
  def show
  end

  # GET /greeting_cards/new
  def new
    @greeting_card = GreetingCard.new
  end

  # GET /greeting_cards/1/edit
  def edit
  end

  # POST /greeting_cards
  # POST /greeting_cards.json
  def create
    @greeting_card = GreetingCard.new(greeting_card_params)
    @greeting_card.image.attach(params[:greeting_card][:image])
    respond_to do |format|
      if @greeting_card.save
        ProcessImageJob.perform_later(@greeting_card.id)
        format.html { redirect_to @greeting_card, notice: 'Greeting card was successfully created.' }
        format.json { render :show, status: :created, location: @greeting_card }
      else
        format.html { render :new }
        format.json { render json: @greeting_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /greeting_cards/1
  # PATCH/PUT /greeting_cards/1.json
  def update
    respond_to do |format|
      if @greeting_card.update(greeting_card_params)
        format.html { redirect_to @greeting_card, notice: 'Greeting card was successfully updated.' }
        format.json { render :show, status: :ok, location: @greeting_card }
      else
        format.html { render :edit }
        format.json { render json: @greeting_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /greeting_cards/1
  # DELETE /greeting_cards/1.json
  def destroy
    @greeting_card.destroy
    respond_to do |format|
      format.html { redirect_to greeting_cards_url, notice: 'Greeting card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_greeting_card
      @greeting_card = GreetingCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def greeting_card_params
      params.require(:greeting_card).permit(:title, :message, :sender_name, :sender_email, :recipient_name, :recipient_email, :status)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greeting_cards_helper.rb
module GreetingCardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/greeting_cards/_form.html.erb
<%= form_with(model: greeting_card, local: true) do |form| %>
  <% if greeting_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(greeting_card.errors.count, "error") %> prohibited this greeting_card from being saved:</h2>

      <ul>
      <% greeting_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :sender_name %>
    <%= form.text_field :sender_name, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :sender_email %>
    <%= form.text_field :sender_email, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :recipient_name %>
    <%= form.text_field :recipient_name, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :recipient_email %>
    <%= form.text_field :recipient_email, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>
<br>

app/views/greeting_cards/edit.html.erb
<h1>Editing Greeting Card</h1>

<%= render 'form', greeting_card: @greeting_card %>

<%= link_to 'Show', @greeting_card %> |
<%= link_to 'Back', greeting_cards_path %>

app/views/greeting_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Greeting Cards - AWS Meetup 2!</h1>
<hr>
<%= link_to 'New Greeting Card', new_greeting_card_path, class: 'btn btn-primary' %>

<br>
<br>

<table class="table table-bordered table-responsive">
  <thead>
    <tr>
      <th>Title</th>
      <th>Message</th>
      <th>Sender name</th>
      <th>Sender email</th>
      <th>Recipient name</th>
      <th>Recipient email</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @greeting_cards.each do |greeting_card| %>
      <tr>
        <td><%= greeting_card.title %></td>
        <td><%= greeting_card.message %></td>
        <td><%= greeting_card.sender_name %></td>
        <td><%= greeting_card.sender_email %></td>
        <td><%= greeting_card.recipient_name %></td>
        <td><%= greeting_card.recipient_email %></td>
        <td><%= greeting_card.status %></td>
        <td><%= link_to 'Show', greeting_card %></td>
        <td><%= link_to 'Edit', edit_greeting_card_path(greeting_card) %></td>
        <td><%= link_to 'Destroy', greeting_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/greeting_cards/new.html.erb
<h1>New Greeting Card</h1>
<hr>
<%= render 'form', greeting_card: @greeting_card %>

<%= link_to 'Back', greeting_cards_path, class: 'btn btn-default' %>

app/views/greeting_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @greeting_card.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @greeting_card.message %>
</p>

<p>
  <strong>Sender name:</strong>
  <%= @greeting_card.sender_name %>
</p>

<p>
  <strong>Sender email:</strong>
  <%= @greeting_card.sender_email %>
</p>

<p>
  <strong>Recipient name:</strong>
  <%= @greeting_card.recipient_name %>
</p>

<p>
  <strong>Recipient email:</strong>
  <%= @greeting_card.recipient_email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @greeting_card.status %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag url_for(@greeting_card.image) if @greeting_card.image.attached? %>
</p>

<%= link_to 'Edit', edit_greeting_card_path(@greeting_card) %> |
<%= link_to 'Back', greeting_cards_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwsMeetup2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-8">
          <%= yield %>
        </div>
        <div class="col-md-2">

        </div>

      </div>
    </div>
  </body>
</html>